spring.application.name=monitoring

spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring
spring.datasource.username=postgres
spring.datasource.password=Blacklotus01
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false


management.endpoint.health.show-details=always


server.port=8081
